system:
  num_client: 5
  num_local_class: 5
  dataset: "ChestXrays"
  model: "ResNet50"
  i_seed: 235235
  num_round: 1
  res_root: "results"

client:
  fed_algo: "FedProx"
  lr: 0.01
  batch_size: 64
  num_local_epoch: 3
  momentum: 0.9
  num_worker: 2